import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, useState, type ReactNode } from "react";
import appCss from "../styles.css?url";
import { supabase } from "@/integrations/supabase/client";
const site="https://smartchains.online";
function SmartChainLoader(){return <main className="grid min-h-screen place-items-center bg-background px-6"><div className="text-center"><img src="/smartchain-logo.svg" alt="SmartChain" className="mx-auto size-16 rounded-2xl"/><h1 className="mt-6 font-display text-2xl font-semibold">SmartChain</h1><p className="mt-2 text-sm text-muted-foreground">Preparing your secure dashboard…</p></div></main>}
function isConfirmed(session:any){return Boolean(session?.user?.email_confirmed_at||session?.user?.confirmed_at);}
function AuthGate({children}:{children:ReactNode}){const [ready,setReady]=useState(false);useEffect(()=>{let active=true;let timer:number|undefined;async function check(){try{const {data}=await supabase.auth.getSession();if(!active)return;const session=data.session;const authPage=window.location.pathname==="/auth";if(!authPage&&!session){window.location.replace("/auth");return}if(!authPage&&session&&!isConfirmed(session)){window.location.replace("/auth?verify=1");return}if(authPage&&isConfirmed(session)&&!window.location.search.includes("reset=1")&&!window.location.search.includes("verify=1")){window.location.replace("/");return}setReady(true)}catch(error){console.error("SmartChain auth initialization failed",error);if(active)setReady(true)}}void check();timer=window.setTimeout(()=>{if(active)setReady(true)},5000);const {data:listener}=supabase.auth.onAuthStateChange((_event,session)=>{if(!active)return;const authPage=window.location.pathname==="/auth";if(!authPage&&!session){window.location.replace("/auth");return}if(!authPage&&session&&!isConfirmed(session)){window.location.replace("/auth?verify=1");return}if(authPage&&isConfirmed(session)&&!window.location.search.includes("reset=1")&&!window.location.search.includes("verify=1")){window.location.replace("/");return}setReady(true)});return()=>{active=false;if(timer)window.clearTimeout(timer);listener.subscription.unsubscribe()}},[]);return ready?children:<SmartChainLoader/>}
function NotFoundComponent(){return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-7xl font-bold">404</h1><h2 className="mt-4 text-xl font-semibold">Page not found</h2><p className="mt-2 text-sm text-muted-foreground">The page you're looking for doesn't exist or has been moved.</p><Link to="/" className="mt-6 inline-block rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Go home</Link></div></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){console.error("SmartChain route error",error);const router=useRouter();return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><img src="/smartchain-logo.svg" alt="SmartChain" className="mx-auto size-16 rounded-2xl"/><h1 className="mt-6 text-xl font-semibold">We couldn't load this page</h1><p className="mt-2 text-sm text-muted-foreground">Please try again or sign in to continue.</p><div className="mt-6 flex justify-center gap-2"><button onClick={()=>{router.invalidate().catch(()=>{});reset()}} className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Try again</button><Link to="/auth" className="rounded-md border px-4 py-2 text-sm">Sign in</Link></div></div></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"},{title:"SmartChain Wallet"},{name:"description",content:"Secure crypto wallet and trading with SmartChain."},{name:"theme-color",content:"#10141b"}],links:[{rel:"canonical",href:site},{rel:"stylesheet",href:appCss},{rel:"icon",href:"/smartchain-logo.svg",type:"image/svg+xml"},{rel:"manifest",href:"/manifest.webmanifest"}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent,pendingComponent:SmartChainLoader,pendingMs:150});
function RootShell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const {queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><AuthGate><Outlet/></AuthGate></QueryClientProvider>}
