import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, useNavigate, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, useState, type ReactNode } from "react";
import appCss from "../styles.css?url";
import { supabase } from "../integrations/supabase/client";
import { reportLovableError } from "../lib/lovable-error-reporting";
const site="https://smartchains.online";
function SmartChainLoader(){return <main className="grid min-h-screen place-items-center bg-background px-6"><div className="text-center"><div className="relative mx-auto grid size-24 place-items-center"><div className="absolute inset-0 animate-spin rounded-full border-4 border-primary/20 border-t-primary"/><img src="/smartchain-logo.svg" alt="SmartChain" className="size-16 rounded-2xl"/></div><h1 className="mt-6 font-display text-2xl font-semibold tracking-tight">SmartChain</h1><p className="mt-2 text-sm text-muted-foreground">Preparing your secure dashboard…</p><div className="mx-auto mt-5 h-1.5 w-48 overflow-hidden rounded-full bg-secondary"><div className="h-full w-1/2 animate-pulse rounded-full bg-primary"/></div></div></main>}
function DashboardActionLoader(){const [show,setShow]=useState(false);useEffect(()=>{let timer:number|undefined;const onClick=(event:MouseEvent)=>{if(window.location.pathname==="/auth")return;const target=event.target as HTMLElement|null;const actionable=target?.closest("button,a,[role='button']");if(!actionable)return;if((actionable as HTMLElement).dataset.noActionLoader==="true")return;if(actionable.getAttribute("aria-label")?.toLowerCase().includes("close"))return;setShow(true);if(timer)window.clearTimeout(timer);timer=window.setTimeout(()=>setShow(false),2000)};document.addEventListener("click",onClick,true);return()=>{document.removeEventListener("click",onClick,true);if(timer)window.clearTimeout(timer)}},[]);if(!show)return null;return <div className="pointer-events-none fixed inset-x-0 top-0 z-[100] h-1 bg-primary"><div className="h-full w-1/3 animate-pulse bg-primary-foreground/80"/><div className="absolute left-1/2 top-3 -translate-x-1/2 rounded-full border border-border bg-background/95 px-3 py-1 text-[11px] font-medium text-muted-foreground shadow-lg">Loading…</div></div>}
function AuthGate({children}:{children:ReactNode}){const navigate=useNavigate();const [ready,setReady]=useState(false);useEffect(()=>{let active=true;let timeout:number|undefined;const isAuthPage=()=>window.location.pathname==="/auth";const isConfirmed=(session:{user?:{email_confirmed_at?:string|null}}|null)=>Boolean(session?.user?.email_confirmed_at);async function checkSession(){const {data}=await supabase.auth.getSession();if(!active)return;const session=data.session;if(!isAuthPage()&&!isConfirmed(session)){setReady(false);void navigate({to:"/auth",replace:true});return}if(isAuthPage()&&isConfirmed(session)&&!window.location.search.includes("reset=1")){setReady(false);void navigate({to:"/",replace:true});return}setReady(true)}void checkSession();timeout=window.setTimeout(()=>{if(!active||ready)return;if(!isAuthPage()){void navigate({to:"/auth",replace:true})}else setReady(true)},5000);const {data:listener}=supabase.auth.onAuthStateChange((_event,session)=>{if(!active)return;const authPage=isAuthPage();if(!authPage&&!isConfirmed(session)){setReady(false);void navigate({to:"/auth",replace:true})}else if(authPage&&isConfirmed(session)&&!window.location.search.includes("reset=1")){setReady(false);void navigate({to:"/",replace:true})}else setReady(true)});return()=>{active=false;listener.subscription.unsubscribe();if(timeout)window.clearTimeout(timeout)}},[navigate,ready]);return ready?<><DashboardActionLoader/>{children}</>:<SmartChainLoader/>}
function NotFoundComponent(){return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-7xl font-bold">404</h1><h2 className="mt-4 text-xl font-semibold">Page not found</h2><p className="mt-2 text-sm text-muted-foreground">The page you're looking for doesn't exist or has been moved.</p><div className="mt-6"><Link to="/" className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Go home</Link></div></div></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){console.error(error);const router=useRouter();useEffect(()=>{reportLovableError(error,{boundary:"tanstack_root_error_component"})},[error]);return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-xl font-semibold">This page didn't load</h1><p className="mt-2 text-sm text-muted-foreground">Something went wrong. Try refreshing or go back.</p><div className="mt-6 flex justify-center gap-2"><button onClick={()=>{router.invalidate();reset()}} className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Try again</button><Link to="/auth" className="rounded-md border px-4 py-2 text-sm">Sign in</Link></div></div></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{title:"SmartChain Wallet"},{name:"description",content:"Secure crypto wallet and trading with SmartChain."},{name:"theme-color",content:"#10141b"},{property:"og:title",content:"SmartChain Wallet"},{property:"og:description",content:"Secure crypto wallet and trading with SmartChain."},{property:"og:type",content:"website"},{property:"og:url",content:site},{property:"og:image",content:`${site}/og-image.svg`},{property:"og:image:width",content:"1200"},{property:"og:image:height",content:"630"},{name:"twitter:card",content:"summary_large_image"},{name:"twitter:title",content:"SmartChain Wallet"},{name:"twitter:description",content:"Secure crypto wallet and trading with SmartChain."},{name:"twitter:image",content:`${site}/og-image.svg`}],links:[{rel:"canonical",href:site},{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"},{rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&family=Space+Grotesk:wght@500;600;700&display=swap"},{rel:"stylesheet",href:appCss},{rel:"icon",href:"/smartchain-logo.svg",type:"image/svg+xml"},{rel:"manifest",href:"/manifest.webmanifest"}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent,pendingComponent:SmartChainLoader,pendingMs:150});
function RootShell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const {queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><AuthGate><Outlet/></AuthGate></QueryClientProvider>}
