import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, useState, type ReactNode } from "react";
import appCss from "../styles.css?url";
import { supabase } from "@/integrations/supabase/client";
const site="https://smartchains.online"; const PENDING_OTP_KEY="smartchain_pending_otp"; const PIN_KEY="smartchain_pin_hash"; const PIN_UNLOCKED_KEY="smartchain_pin_unlocked_at";
function SmartChainLoader(){return <main className="grid min-h-screen place-items-center bg-background px-6"><div className="text-center"><img src="/smartchain-logo.svg" alt="SmartChain" className="mx-auto size-16 rounded-2xl"/><h1 className="mt-6 font-display text-2xl font-semibold">SmartChain</h1><p className="mt-2 text-sm text-muted-foreground">Preparing your secure dashboard…</p></div></main>}
function isConfirmed(session:any){return Boolean(session?.user?.email_confirmed_at||session?.user?.confirmed_at);}
async function hashPin(pin:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(pin));return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,"0")).join("")}
function ScreenLock(){const [locked,setLocked]=useState(false),[pin,setPin]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");useEffect(()=>{const check=()=>{const enabled=Boolean(localStorage.getItem(PIN_KEY));const last=Number(sessionStorage.getItem(PIN_UNLOCKED_KEY)||0);setLocked(enabled&&(last===0||Date.now()-last>=5*60*1000));};check();const onVisibility=()=>{if(document.visibilityState==="visible")check()};document.addEventListener("visibilitychange",onVisibility);const timer=window.setInterval(check,15000);return()=>{document.removeEventListener("visibilitychange",onVisibility);window.clearInterval(timer)}},[]);if(!locked)return null;async function unlock(){if(busy)return;if(!/^\d{4,6}$/.test(pin))return setError("Enter your 4–6 digit PIN.");setBusy(true);setError("");try{const expected=localStorage.getItem(PIN_KEY);const actual=await hashPin(pin);if(!expected||actual!==expected){setError("Incorrect PIN. Try again.");setPin("");return}sessionStorage.setItem(PIN_UNLOCKED_KEY,String(Date.now()));setLocked(false);setPin("")}catch{setError("Unable to unlock. Please try again.")}finally{setBusy(false)}}return <div className="fixed inset-0 z-[9999] grid place-items-center bg-background/98 px-5 backdrop-blur-md"><section className="w-full max-w-sm rounded-3xl border border-border bg-card p-6 text-center shadow-2xl"><img src="/smartchain-logo.svg" alt="SmartChain" className="mx-auto size-14 rounded-2xl"/><h2 className="mt-5 text-xl font-semibold">SmartChain locked</h2><p className="mt-2 text-sm text-muted-foreground">Enter your PIN to unlock your wallet.</p><input autoFocus type="password" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,6))} onKeyDown={e=>{if(e.key==="Enter")void unlock()}} className="mt-5 w-full rounded-xl border bg-background px-4 py-4 text-center text-2xl tracking-[0.5em]" placeholder="••••"/><button type="button" disabled={busy} onClick={()=>void unlock()} className="mt-4 w-full rounded-xl bg-primary px-4 py-3 font-semibold text-primary-foreground disabled:opacity-50">{busy?"Unlocking…":"Unlock"}</button>{error&&<p className="mt-3 text-sm text-destructive">{error}</p>}<p className="mt-4 text-xs text-muted-foreground">Your account remains protected by your normal SmartChain sign-in.</p></section></div>}
function AuthGate({children}:{children:ReactNode}){const [ready,setReady]=useState(false);useEffect(()=>{let active=true;let timer:number|undefined;const isAuth=()=>window.location.pathname==="/auth";const isVerify=()=>new URLSearchParams(window.location.search).get("verify")==="1";const isReset=()=>new URLSearchParams(window.location.search).get("reset")==="1";async function check(){try{const {data}=await supabase.auth.getSession();if(!active)return;const session=data.session;const authPage=isAuth();const pendingOtp=sessionStorage.getItem(PENDING_OTP_KEY)==="1";if(!authPage&&!session){window.location.replace("/auth");return}if(!authPage&&session&&!isConfirmed(session)){window.location.replace("/auth?verify=1");return}if(authPage&&isConfirmed(session)&&!pendingOtp&&!isVerify()&&!isReset()){window.location.replace("/");return}setReady(true)}catch(error){console.error("SmartChain auth initialization failed",error);if(active)setReady(true)}}void check();timer=window.setTimeout(()=>{if(active)setReady(true)},5000);const {data:listener}=supabase.auth.onAuthStateChange((_event,session)=>{if(!active)return;const authPage=isAuth();const pendingOtp=sessionStorage.getItem(PENDING_OTP_KEY)==="1";if(!authPage&&!session){window.location.replace("/auth");return}if(!authPage&&session&&!isConfirmed(session)){window.location.replace("/auth?verify=1");return}if(authPage){if(isVerify()||isReset()||pendingOtp){setReady(true);return}if(isConfirmed(session)){window.location.replace("/");return}}setReady(true)});return()=>{active=false;if(timer)window.clearTimeout(timer);listener.subscription.unsubscribe()}},[]);return ready?children:<SmartChainLoader/>}
function NotFoundComponent(){return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-7xl font-bold">404</h1><h2 className="mt-4 text-xl font-semibold">Page not found</h2><p className="mt-2 text-sm text-muted-foreground">The page you're looking for doesn't exist or has been moved.</p><Link to="/" className="mt-6 inline-block rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Go home</Link></div></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){console.error("SmartChain route error",error);const router=useRouter();return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><img src="/smartchain-logo.svg" alt="SmartChain" className="mx-auto size-16 rounded-2xl"/><h1 className="mt-6 text-xl font-semibold">We couldn't load this page</h1><p className="mt-2 text-sm text-muted-foreground">Please try again or sign in to continue.</p><div className="mt-6 flex justify-center gap-2"><button onClick={()=>{router.invalidate().catch(()=>{});reset()}} className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Try again</button><Link to="/auth" className="rounded-md border px-4 py-2 text-sm">Sign in</Link></div></div></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"},{title:"SmartChain Wallet"},{name:"description",content:"Secure crypto wallet and trading with SmartChain."},{name:"theme-color",content:"#10141b"}],links:[{rel:"canonical",href:site},{rel:"stylesheet",href:appCss},{rel:"icon",href:"/smartchain-logo.svg",type:"image/svg+xml"},{rel:"manifest",href:"/manifest.webmanifest"}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent,pendingComponent:SmartChainLoader,pendingMs:150});
function RootShell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const {queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><AuthGate><Outlet/><ScreenLock/></AuthGate></QueryClientProvider>}
