import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { AppHeader } from "@/components/wallet/AppHeader";
import { BalanceCard } from "@/components/wallet/BalanceCard";
import { QuickActions } from "@/components/wallet/QuickActions";
import { AssetList } from "@/components/wallet/AssetList";
import { RecentActivity } from "@/components/wallet/RecentActivity";
import { BottomNavigation } from "@/components/wallet/BottomNavigation";
import { InstallPrompt } from "@/components/wallet/InstallPrompt";
import { SmartChainLoader } from "@/components/wallet/SmartChainLoader";
import { useNotifications, usePortfolio, useProfile, useTransactions } from "@/hooks/useWalletData";
const title = "SmartChain Wallet — Secure Crypto Dashboard"; const description = "SmartChain is a secure crypto wallet and trading platform."; const site = "https://smartchains.online";
export const Route = createFileRoute("/")({head: () => ({meta: [{title},{name:"description",content:description},{property:"og:title",content:title},{property:"og:description",content:description},{property:"og:image",content:`${site}/og-image.svg`},{property:"og:url",content:site},{name:"twitter:card",content:"summary_large_image"},{name:"twitter:image",content:`${site}/og-image.svg`},{name:"twitter:url",content:site}]}),component:Dashboard});
function Dashboard(){const [splash,setSplash]=useState(true);const p=usePortfolio();const tx=useTransactions(5);const n=useNotifications();const profile=useProfile();const error=p.markets.error;useEffect(()=>{const id=window.setTimeout(()=>setSplash(false),1000);return()=>window.clearTimeout(id)},[]);if(splash)return <SmartChainLoader/>;const blocked=profile.data?.account_status==="blocked";return <div className="min-h-screen bg-background pb-24"><AppHeader notificationCount={n.unread}/><main className="mx-auto max-w-lg space-y-6 px-4 pt-5"><h1 className="sr-only">SmartChain wallet dashboard</h1>{blocked&&<section className="rounded-2xl border border-destructive/40 bg-destructive/10 p-4"><p className="font-semibold text-destructive">Account blocked</p><p className="mt-1 text-sm text-muted-foreground">Your account has been blocked by SmartChain administration. Transfers and withdrawals are disabled. Please contact support.</p></section>}<BalanceCard portfolio={p.portfolio} loading={false}/><QuickActions/><AssetList positions={p.positions} loading={false} error={error?(error as Error).message:null} onRetry={()=>{void p.holdings.refetch();void p.markets.refetch();void tx.refetch();void profile.refetch()}} onSelect={position=>{window.location.href=`/asset/${position.market.id}`}} onViewAll={()=>{window.location.href="/markets"}}/><RecentActivity transactions={tx.data??[]} loading={tx.isLoading}/></main><InstallPrompt/><BottomNavigation active="home"/></div>}
