import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Copy, QrCode } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { SUPPORTED_ASSETS } from "@/data/assets";
export const Route=createFileRoute("/receive")({component:Receive});
type Wallet={asset_id:string;symbol:string;name:string;network:string;deposit_address:string|null;confirmations_required:number};type Net={asset_id:string;network:string;network_code:string;confirmations_required:number};
function Receive(){const [wallets,setWallets]=useState<Wallet[]>([]);const [nets,setNets]=useState<Net[]>([]);const [selected,setSelected]=useState(SUPPORTED_ASSETS[0]?.id||"bitcoin");const [network,setNetwork]=useState("");useEffect(()=>{void(async()=>{const [w,n]=await Promise.all([supabase.from("coin_wallets").select("asset_id,symbol,name,network,deposit_address,confirmations_required").eq("enabled",true),supabase.from("asset_networks" as never).select("asset_id,network,network_code,confirmations_required").eq("enabled",true)]);setWallets((w.data??[]) as Wallet[]);setNets((n.data??[]) as Net[])})()},[]);const asset=SUPPORTED_ASSETS.find(a=>a.id===selected);const available=nets.filter(n=>n.asset_id===selected);useEffect(()=>{if(available.length&&!available.some(n=>n.network===network))setNetwork(available[0].network)},[selected,nets]);const chosenNet=available.find(n=>n.network===network);const wallet=wallets.find(w=>w.asset_id===selected&&w.network===network);async function copy(){if(!wallet?.deposit_address)return;await navigator.clipboard.writeText(wallet.deposit_address);toast.success("Deposit address copied")}
return <main className="mx-auto max-w-lg px-4 pb-24 pt-5"><Link to="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft size={17}/> Dashboard</Link><h1 className="mt-5 text-2xl font-semibold">Deposit crypto</h1><p className="mt-1 text-sm text-muted-foreground">Choose the coin and exact network before sending.</p><label className="mt-5 block text-sm font-medium">Coin<select value={selected} onChange={e=>setSelected(e.target.value)} className="mt-2 w-full rounded-xl border bg-background p-3">{SUPPORTED_ASSETS.map(a=><option key={a.id} value={a.id}>{a.name} ({a.symbol})</option>)}</select></label><label className="mt-4 block text-sm font-medium">Network<select value={network} onChange={e=>setNetwork(e.target.value)} className="mt-2 w-full rounded-xl border bg-background p-3"><option value="">Select network</option>{available.map(n=><option key={n.network} value={n.network}>{n.network} ({n.network_code})</option>)}</select></label><section className="mt-5 rounded-3xl border bg-card p-6 text-center"><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-primary/10 text-primary"><QrCode/></div><h2 className="mt-3 text-xl font-semibold">{asset?.name} ({asset?.symbol})</h2>{chosenNet&&<p className="mt-1 text-sm text-muted-foreground">Network: {chosenNet.network}</p>}{wallet?.deposit_address?<><img className="mx-auto mt-6 size-56 rounded-xl border bg-white p-2" alt={`${asset?.symbol} deposit QR`} src={`https://quickchart.io/qr?size=320&margin=2&text=${encodeURIComponent(wallet.deposit_address)}`}/><div className="mt-5 break-all rounded-xl bg-secondary p-3 text-left text-xs">{wallet.deposit_address}</div><button onClick={()=>void copy()} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-3 font-semibold text-primary-foreground"><Copy size={17}/> Copy address</button><div className="mt-5 rounded-xl bg-secondary p-4 text-left text-xs text-muted-foreground"><p><b className="text-foreground">Settlement:</b> Your deposit is credited after {wallet.confirmations_required||chosenNet?.confirmations_required||1} network confirmation{(wallet.confirmations_required||chosenNet?.confirmations_required||1)===1?"":"s"}.</p><p className="mt-2"><b className="text-foreground">Important:</b> Send only {asset?.symbol} using the selected {chosenNet?.network} network. Deposits sent on a different network or to the wrong address may be permanently lost and may not be recoverable.</p></div></>:<div className="mt-6 rounded-xl bg-secondary p-4 text-sm text-muted-foreground">No deposit address is configured for this coin and network yet. Please choose another network or contact support.</div>}</section></main>}
