import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Copy, QrCode } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useMarkets } from "@/hooks/useMarkets";
export const Route=createFileRoute("/receive")({component:Receive});
type Wallet={asset_id:string;symbol:string;name:string;network:string;deposit_address:string|null};type Fee={network:string;fee_amount:number;fee_currency:string};
function Receive(){const {markets,isLoading}=useMarkets();const [wallets,setWallets]=useState<Wallet[]>([]);const [fees,setFees]=useState<Fee[]>([]);const [selected,setSelected]=useState("");useEffect(()=>{void (async()=>{const [w,f]=await Promise.all([supabase.from("coin_wallets").select("asset_id,symbol,name,network,deposit_address").eq("enabled",true),supabase.from("network_fees").select("network,fee_amount,fee_currency").eq("enabled",true)]);setWallets((w.data??[]) as Wallet[]);setFees((f.data??[]) as Fee[])})()},[]);const list=wallets.length?wallets:markets.map(m=>({asset_id:m.id,symbol:m.symbol,name:m.name,network:"Not configured",deposit_address:null}));const coin=list.find(x=>x.asset_id===selected)||list[0];const fee=fees.find(x=>x.network===coin?.network);async function copy(){if(!coin?.deposit_address)return;await navigator.clipboard.writeText(coin.deposit_address);toast.success("Wallet address copied")}
 return <main className="mx-auto max-w-lg px-4 pb-24 pt-5"><Link to="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft size={17}/> Dashboard</Link><h1 className="mt-5 text-2xl font-semibold">Deposit crypto</h1><p className="mt-1 text-sm text-muted-foreground">Select a coin to view its configured deposit address and QR code.</p>{isLoading?<p className="mt-6 text-sm">Loading coins…</p>:<><div className="mt-5 flex gap-2 overflow-x-auto pb-1">{list.map(x=><button key={x.asset_id} onClick={()=>setSelected(x.asset_id)} className={`shrink-0 rounded-xl border px-4 py-2 text-sm font-semibold ${x.asset_id===coin?.asset_id?"border-primary bg-primary/10 text-primary":""}`}>{x.symbol}</button>)}</div>{coin&&<section className="mt-5 rounded-3xl border bg-card p-6 text-center"><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-primary/10 text-primary"><QrCode/></div><h2 className="mt-3 text-xl font-semibold">{coin.name} ({coin.symbol})</h2><p className="mt-1 text-sm text-muted-foreground">Network: {coin.network}</p>{coin.deposit_address?<><img className="mx-auto mt-6 size-56 rounded-xl border bg-white p-2" alt={`${coin.symbol} deposit QR`} src={`https://quickchart.io/qr?size=320&margin=2&text=${encodeURIComponent(coin.deposit_address)}`}/><div className="mt-5 break-all rounded-xl bg-secondary p-3 text-left text-xs">{coin.deposit_address}</div><button onClick={()=>void copy()} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-3 font-semibold text-primary-foreground"><Copy size={17}/> Copy address</button>{fee&&<p className="mt-4 text-xs text-muted-foreground">Configured network fee: {fee.fee_amount} {fee.fee_currency}</p>}</>:<div className="mt-6 rounded-xl bg-secondary p-4 text-sm text-muted-foreground">Deposit wallet not configured yet. An administrator must add the wallet address before deposits are enabled.</div>}<p className="mt-5 text-xs text-muted-foreground">Only send {coin.symbol} on the displayed network. Sending another asset or network may result in permanent loss.</p></section>}</>}</main>;
}