import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Check, Loader2 } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { usePreferences, useProfile } from "@/hooks/useWalletData";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/settings")({component:Settings});
const CURRENCIES=["USD","EUR","GBP","NGN","CAD","AUD","JPY","CNY","INR","AED","ZAR","KES","GHS","BRL","MXN","CHF","KRW","SGD","HKD","TRY"];
function Settings(){const profile=useProfile(),prefs=usePreferences();const [name,setName]=useState(""),[currency,setCurrency]=useState("USD"),[security,setSecurity]=useState(true),[transactions,setTransactions]=useState(true),[marketing,setMarketing]=useState(false),[hideBalance,setHideBalance]=useState(false),[saving,setSaving]=useState(false);
useEffect(()=>{if(profile.data?.display_name)setName(profile.data.display_name)},[profile.data?.display_name]);useEffect(()=>{if(prefs.data){setCurrency(prefs.data.currency||"USD");setSecurity(!!prefs.data.notify_security);setTransactions(!!prefs.data.notify_transactions);setMarketing(!!prefs.data.notify_marketing);setHideBalance(!!prefs.data.hide_balance)}},[prefs.data]);
async function save(){setSaving(true);try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("You must be signed in.");const {error:pe}=await supabase.from("profiles").update({display_name:name.trim()||"SmartChain user"}).eq("id",user.id);if(pe)throw pe;const {error}=await supabase.from("user_preferences").upsert({user_id:user.id,currency,hide_balance:hideBalance,notify_security:security,notify_transactions:transactions,notify_marketing:marketing},{onConflict:"user_id"});if(error)throw error;await Promise.all([profile.refetch(),prefs.refetch()]);toast.success("All settings saved")}catch(e){toast.error(e instanceof Error?e.message:"Unable to save settings")}finally{setSaving(false)}}
const Toggle=({title,text,checked,onChange}:{title:string;text:string;checked:boolean;onChange:(v:boolean)=>void})=><label className="flex items-center justify-between gap-4 rounded-xl bg-secondary p-4"><span><b className="block text-sm">{title}</b><span className="text-xs text-muted-foreground">{text}</span></span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="size-5 accent-primary"/></label>;
return <main className="mx-auto max-w-lg px-4 pb-24 pt-5"><Link to="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft size={17}/> Dashboard</Link><h1 className="mt-5 text-2xl font-semibold">Settings</h1><p className="mt-1 text-sm text-muted-foreground">Manage your SmartChain account preferences.</p><section className="mt-5 space-y-5 rounded-2xl border border-border bg-card p-5"><label className="block text-sm font-medium">Display name<input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border border-input bg-background px-3 py-3" placeholder="Your name"/></label><label className="block text-sm font-medium">Currency<select value={currency} onChange={e=>setCurrency(e.target.value)} className="mt-2 w-full rounded-xl border border-input bg-background px-3 py-3">{CURRENCIES.map(c=><option key={c} value={c}>{c}</option>)}</select></label><Toggle title="Hide balance" text="Hide wallet balances on your dashboard." checked={hideBalance} onChange={setHideBalance}/><Toggle title="Security notifications" text="Alerts about account security." checked={security} onChange={setSecurity}/><Toggle title="Transaction notifications" text="Updates about wallet activity." checked={transactions} onChange={setTransactions}/><Toggle title="Marketing notifications" text="News and product updates." checked={marketing} onChange={setMarketing}/><button type="button" disabled={saving} onClick={()=>void save()} className="flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 font-semibold text-primary-foreground disabled:opacity-50">{saving?<Loader2 size={17} className="animate-spin"/>:<Check size={17}/>}{saving?"Saving…":"Save settings"}</button></section><Link to="/kyc" className="mt-4 block rounded-2xl border border-border bg-card p-4 hover:bg-secondary"><b>KYC verification</b><span className="mt-1 block text-sm text-muted-foreground">Verify your identity and manage your verification status.</span></Link></main>}
