import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowLeft, ImagePlus, Send, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/support")({ component: Support });
type Msg={id:string;message:string|null;attachment_path:string|null;is_admin:boolean;created_at:string};
type ViewMsg=Msg&{attachmentUrl:string|null};
function Support(){
 const [uid,setUid]=useState<string|null>(null),[ticket,setTicket]=useState<string|null>(null),[messages,setMessages]=useState<ViewMsg[]>([]),[text,setText]=useState(""),[file,setFile]=useState<File|null>(null),[sending,setSending]=useState(false),[loading,setLoading]=useState(true);const endRef=useRef<HTMLDivElement>(null);
 const hydrate=useCallback(async(rows:Msg[])=>{const result=await Promise.all(rows.map(async m=>{if(!m.attachment_path)return {...m,attachmentUrl:null};const {data}=await supabase.storage.from("support-attachments").createSignedUrl(m.attachment_path,60*60);return {...m,attachmentUrl:data?.signedUrl??null}}));setMessages(result)},[]);
 const load=useCallback(async()=>{setLoading(true);try{const {data:a,error:authError}=await supabase.auth.getUser();if(authError)throw authError;if(!a.user)throw new Error("Please sign in to use support chat.");setUid(a.user.id);let {data:t,error:ticketError}=await supabase.from("support_tickets").select("id").eq("user_id",a.user.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(ticketError)throw ticketError;if(!t){const r=await supabase.from("support_tickets").insert({user_id:a.user.id,subject:"Support request"}).select("id").single();if(r.error)throw r.error;t=r.data}setTicket(t.id);const {data:m,error:messageError}=await supabase.from("support_messages").select("id,message,attachment_path,is_admin,created_at").eq("ticket_id",t.id).order("created_at");if(messageError)throw messageError;await hydrate((m??[]) as Msg[])}catch(e){toast.error(e instanceof Error?e.message:"Unable to load support chat")}finally{setLoading(false)}},[hydrate]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!ticket)return;const channel=supabase.channel(`support-${ticket}`).on("postgres_changes",{event:"*",schema:"public",table:"support_messages",filter:`ticket_id=eq.${ticket}`},()=>{void load()}).subscribe();return()=>{void supabase.removeChannel(channel)}},[ticket,load]);
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"})},[messages]);
 async function send(){if(!uid||!ticket||(!text.trim()&&!file))return;setSending(true);try{let path:string|null=null;if(file){if(!file.type.startsWith("image/"))throw new Error("Only images are allowed.");if(file.size>8*1024*1024)throw new Error("Image must be 8 MB or smaller.");const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";path=`${uid}/${crypto.randomUUID()}.${ext}`;const r=await supabase.storage.from("support-attachments").upload(path,file,{contentType:file.type,upsert:false});if(r.error)throw r.error}const r=await supabase.from("support_messages").insert({ticket_id:ticket,user_id:uid,message:text.trim()||null,attachment_path:path,is_admin:false});if(r.error)throw r.error;setText("");setFile(null);await load()}catch(e){toast.error(e instanceof Error?e.message:"Unable to send message")}finally{setSending(false)}}
 return <main className="mx-auto max-w-lg px-4 pb-24 pt-5"><Link to="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft size={17}/> Dashboard</Link><h1 className="mt-5 text-2xl font-semibold">Support chat</h1><p className="mt-1 text-sm text-muted-foreground">Chat with support and attach screenshots.</p><section className="mt-5 rounded-2xl border bg-card p-4"><div className="min-h-80 space-y-3">{loading?<div className="grid min-h-80 place-items-center text-sm text-muted-foreground"><Loader2 className="animate-spin" size={22}/></div>:messages.length===0?<p className="py-12 text-center text-sm text-muted-foreground">How can we help?</p>:messages.map(m=><div key={m.id} className={`max-w-[85%] rounded-2xl p-3 text-sm ${m.is_admin?"bg-secondary":"ml-auto bg-primary text-primary-foreground"}`}>{m.message&&<div>{m.message}</div>}{m.attachmentUrl&&<a href={m.attachmentUrl} target="_blank" rel="noreferrer"><img src={m.attachmentUrl} alt="Support attachment" className="mt-2 max-h-56 rounded-xl"/></a>}<p className="mt-1 text-[10px] opacity-60">{m.is_admin?"Support":"You"} · {new Date(m.created_at).toLocaleString()}</p></div>)}<div ref={endRef}/></div><div className="mt-4 flex items-end gap-2"><label className="grid size-11 shrink-0 cursor-pointer place-items-center rounded-xl border"><ImagePlus size={19}/><input type="file" accept="image/*" className="hidden" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message…" className="min-h-11 min-w-0 flex-1 resize-none rounded-xl border bg-background p-3 text-sm"/><button disabled={sending||(!text.trim()&&!file)} onClick={()=>void send()} className="grid size-11 place-items-center rounded-xl bg-primary text-primary-foreground disabled:opacity-50">{sending?<Loader2 className="animate-spin" size={18}/>:<Send size={18}/>}</button></div>{file&&<p className="mt-2 text-xs text-muted-foreground">Ready to send: {file.name}</p>}</section></main>;
}
