import type { AssetPosition } from "@/types/wallet";
import { formatAmount, formatFiat } from "@/lib/format";
import { CryptoLogo } from "./CryptoLogo";
import { PriceChange } from "./PriceChange";
interface AssetRowProps { position: AssetPosition; showHolding?: boolean; onSelect?: (position: AssetPosition) => void; }
const NETWORKS:Record<string,string>={bitcoin:"Bitcoin",ethereum:"Ethereum",tether:"Ethereum (ERC-20)","tether-trc20":"TRON (TRC-20)",binancecoin:"BNB Smart Chain (BEP-20)",solana:"Solana",ripple:"XRP Ledger","usd-coin":"Ethereum (ERC-20)",cardano:"Cardano",dogecoin:"Dogecoin",tron:"TRON","avalanche-2":"Avalanche C-Chain",chainlink:"Ethereum (ERC-20)","polygon-ecosystem-token":"Polygon",litecoin:"Litecoin",polkadot:"Polkadot"};
function compact(value:number){if(!Number.isFinite(value)||value<=0)return "—";return new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:2}).format(value)}
function labelFor(market:{id:string;name:string}){if(market.id==="tether")return "USDT (ERC20)";if(market.id==="tether-trc20")return "USDT (TRC20)";return market.name}
function pairFor(market:{id:string;symbol:string}){return market.id==="tether"||market.id==="tether-trc20"?"USDT/USDT":`${market.symbol}/USDT`}
function EthereumMark(){return <svg viewBox="0 0 256 417" aria-hidden="true" className="h-2.5 w-2 fill-white drop-shadow-sm"><path d="M127.9 0 125.1 9.5v271.7l2.8 2.8 127.9-75.6L127.9 0Z" opacity=".95"/><path d="m127.9 0-127.9 208.4L127.9 284V0Z" opacity=".72"/><path d="m127.9 308.2-1.6 2V415l1.6 2 128-180.3-128 71.5Z" opacity=".95"/><path d="M127.9 417V308.2L0 236.7 127.9 417Z" opacity=".72"/><path d="m127.9 284 127.9-75.6-127.9 58.2V284Z" opacity=".86"/><path d="m0 208.4 127.9 75.6v-17.4L0 208.4Z" opacity=".6"/></svg>}
function NetworkBadge({badge}:{badge:"TRC20"|"ERC20"}){const erc=badge==="ERC20";return <span className={`absolute -bottom-1 -right-2 flex items-center gap-0.5 rounded-full border-2 border-background px-1.5 py-0.5 text-[7px] font-bold tracking-tight text-white shadow-md ${erc?"bg-[#627eea]":"bg-red-600"}`}>{erc&&<EthereumMark/>}{badge}</span>}
export function AssetRow({position,showHolding=true,onSelect}:AssetRowProps){const{market,balance,fiatValue}=position;const network=NETWORKS[market.id]??"Supported network";const stable=market.id==="tether"||market.id==="tether-trc20";const badge=market.id==="tether-trc20"?"TRC20":market.id==="tether"?"ERC20":null;return <li><button type="button" onClick={()=>onSelect?.(position)} aria-label={`${labelFor(market)} details`} className="flex w-full items-center gap-3 rounded-[10px] px-3 py-3 text-left transition-colors hover:bg-secondary focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring"><span className="relative"><CryptoLogo src={market.image} symbol={market.symbol}/>{badge&&<NetworkBadge badge={badge}/>}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{labelFor(market)}</span><span className="block truncate text-xs font-semibold text-foreground">{pairFor(market)}</span><span className="block truncate text-[11px] text-muted-foreground">{network}</span></span><span className="text-right"><span className="block text-sm font-medium tabular-nums">{formatFiat(market.price)} USDT</span><span className="block text-[11px] tabular-nums text-muted-foreground">MCap {compact(market.marketCap)} USDT</span>{showHolding&&<span className="block text-[11px] tabular-nums text-muted-foreground">{formatAmount(balance,stable?"USDT":market.symbol)} • {formatFiat(fiatValue)}</span>}<PriceChange value={market.changePercent24h} className="block text-xs"/></span></button></li>}
