import { useEffect, useMemo, useRef } from "react";
import { createChart, ColorType, CrosshairMode, CandlestickSeries, LineSeries, HistogramSeries } from "lightweight-charts";
import type { ChartPoint } from "@/services/marketApi";

function rsi(values:number[], period=14){const out:(number|null)[]=Array(values.length).fill(null);if(values.length<=period)return out;let gain=0,loss=0;for(let i=1;i<=period;i++){const d=values[i]-values[i-1];gain+=Math.max(d,0);loss+=Math.max(-d,0);}let avgGain=gain/period,avgLoss=loss/period;out[period]=avgLoss===0?100:100-100/(1+avgGain/avgLoss);for(let i=period+1;i<values.length;i++){const d=values[i]-values[i-1];avgGain=(avgGain*(period-1)+Math.max(d,0))/period;avgLoss=(avgLoss*(period-1)+Math.max(-d,0))/period;out[i]=avgLoss===0?100:100-100/(1+avgGain/avgLoss);}return out;}

export function TradingChart({points}:{points:ChartPoint[]}){
 const priceRef=useRef<HTMLDivElement>(null);const rsiRef=useRef<HTMLDivElement>(null);
 const candles=useMemo(()=>{return points.map((p,i)=>{const prev=points[i-1]?.price??p.price;const high=Math.max(prev,p.price)*(1+0.0015);const low=Math.min(prev,p.price)*(1-0.0015);return {time:Math.floor(p.t/1000) as any,open:prev,high,low,close:p.price,volume:Math.max(Math.abs(p.price-prev),p.price*0.0001)}).filter(x=>x.close>0);},[points]);
 const rsiData=useMemo(()=>rsi(candles.map(c=>c.close)).map((v,i)=>v==null?null:{time:candles[i].time,value:v}).filter(Boolean) as {time:any,value:number}[],[candles]);
 useEffect(()=>{if(!priceRef.current||candles.length<2)return;const el=priceRef.current;el.innerHTML="";const chart=createChart(el,{autoSize:true,height:330,layout:{background:{type:ColorType.Solid,color:"transparent"},textColor:"#8f96a3"},grid:{vertLines:{color:"rgba(128,128,128,.08)"},horzLines:{color:"rgba(128,128,128,.08)"}},crosshair:{mode:CrosshairMode.Normal},rightPriceScale:{borderVisible:false},timeScale:{borderVisible:false,timeVisible:true,secondsVisible:false}});const series=chart.addSeries(CandlestickSeries,{upColor:"#16a34a",downColor:"#ef4444",borderVisible:false,wickUpColor:"#16a34a",wickDownColor:"#ef4444"});series.setData(candles);const volume=chart.addSeries(HistogramSeries,{priceFormat:{type:"volume"},priceScaleId:"",color:"rgba(120,120,120,.25)"});volume.priceScale().applyOptions({scaleMargins:{top:.82,bottom:0}});volume.setData(candles.map(c=>({time:c.time,value:c.volume,color:c.close>=c.open?"rgba(22,163,74,.35)":"rgba(239,68,68,.35)"})));chart.timeScale().fitContent();const ro=new ResizeObserver(()=>chart.applyOptions({width:el.clientWidth}));ro.observe(el);return()=>{ro.disconnect();chart.remove();}},[candles]);
 useEffect(()=>{if(!rsiRef.current||rsiData.length<1)return;const el=rsiRef.current;el.innerHTML="";const chart=createChart(el,{autoSize:true,height:125,layout:{background:{type:ColorType.Solid,color:"transparent"},textColor:"#8f96a3"},grid:{vertLines:{color:"rgba(128,128,128,.06)"},horzLines:{color:"rgba(128,128,128,.06)"}},rightPriceScale:{borderVisible:false},timeScale:{visible:false}});const line=chart.addSeries(LineSeries,{color:"#8b5cf6",lineWidth:2});line.setData(rsiData);chart.timeScale().fitContent();const ro=new ResizeObserver(()=>chart.applyOptions({width:el.clientWidth}));ro.observe(el);return()=>{ro.disconnect();chart.remove();}},[rsiData]);
 if(candles.length<2)return <div className="grid h-[330px] place-items-center text-sm text-muted-foreground">Chart data is temporarily unavailable.</div>;
 return <div className="space-y-2"><div className="overflow-hidden rounded-2xl border border-border/70 bg-gradient-to-b from-secondary/40 to-transparent shadow-[0_18px_45px_rgba(0,0,0,.22)]"><div ref={priceRef} className="h-[330px] w-full"/></div><div className="rounded-2xl border border-border/70 bg-secondary/10 px-2 pt-1"><div className="flex items-center justify-between px-1 text-[10px] text-muted-foreground"><span>RSI (14)</span><span>70 · 30</span></div><div ref={rsiRef} className="h-[125px] w-full"/></div></div>;
}
