import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowDownToLine, Send, Loader2, TrendingUp } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useMarkets, useMarketChart } from "@/hooks/useMarkets";
import { useHoldings, useCreateTransaction } from "@/hooks/useWalletData";
import { formatFiat } from "@/lib/format";
import { TradingChart } from "@/components/wallet/TradingChart";

export const Route=createFileRoute("/asset/$assetId")({component:AssetDetails});
function AssetDetails(){
 const {assetId}=Route.useParams();const {markets,isLoading}=useMarkets();const {data:holdings=[]}=useHoldings();const [days,setDays]=useState(7);const {data:chart=[],isLoading:chartLoading}=useMarketChart(assetId,days);const createTrade=useCreateTransaction();const [side,setSide]=useState<"buy"|"sell">("buy");const [amount,setAmount]=useState("");
 const market=markets.find(a=>a.id===assetId);const balance=Number(holdings.find(h=>h.asset_id===assetId)?.balance??0);
 if(isLoading)return <main className="mx-auto max-w-lg p-5">Loading asset…</main>;if(!market)return <main className="mx-auto max-w-lg p-5">Asset not found.</main>;
 const positive=market.changePercent24h>=0;const fiatValue=Number(amount||0)*market.price;
 async function submitTrade(){const quantity=Number(amount);if(!Number.isFinite(quantity)||quantity<=0)return;try{const reference=await createTrade.mutateAsync({type:"swap",asset_id:market.id,symbol:market.symbol,amount:quantity,fiat_value:quantity*market.price,network:"Market",note:`${side.toUpperCase()} ${market.symbol}`});setAmount("");toast.success(`${side==="buy"?"Buy":"Sell"} request created`,{description:`Reference: ${reference}`})}catch(error){toast.error(error instanceof Error?error.message:"Unable to create trade request")}}
 return <main className="mx-auto max-w-lg px-4 pb-28 pt-5"><Link to="/trade" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft size={17}/>Choose another coin</Link><section className="mt-5 rounded-3xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center gap-3"><div className="grid size-12 shrink-0 place-items-center overflow-hidden rounded-full bg-secondary">{market.image?<img src={market.image} alt="" className="size-12 rounded-full"/>:<span className="text-sm font-bold">{market.symbol.slice(0,3)}</span>}</div><div><h1 className="text-2xl font-semibold">{market.name}</h1><p className="text-sm text-muted-foreground">{market.symbol}/USD</p></div></div><div className="mt-7"><p className="text-4xl font-semibold tracking-tight">{formatFiat(market.price)}</p><p className={`mt-1 text-base font-medium ${positive?"text-success":"text-destructive"}`}>{positive?"▲":"▼"} {Math.abs(market.changePercent24h).toFixed(2)}% today</p></div>
 <div className="mt-5 flex items-center gap-2 overflow-x-auto rounded-xl bg-secondary p-1">{[[1,"1D"],[7,"1W"],[30,"1M"],[90,"3M"]].map(([d,label])=><button key={label} type="button" onClick={()=>setDays(Number(d))} className={`rounded-lg px-4 py-2 text-xs whitespace-nowrap ${days===d?"bg-background font-semibold shadow-sm":"text-muted-foreground"}`}>{label}</button>)}</div>
 <div className="mt-3 flex items-center justify-between"><span className="text-xs font-medium text-muted-foreground">Candles · Volume · RSI (14)</span><span className="text-[10px] text-muted-foreground">70 / 30 levels</span></div>
 <div className="mt-2">{chartLoading?<div className="grid h-[330px] place-items-center rounded-2xl border border-border/70 bg-secondary/20 text-sm text-muted-foreground">Loading live chart…</div>:<TradingChart points={chart}/>}</div>
 <p className="mt-2 text-center text-xs text-muted-foreground">Exchange-style chart • Drag, zoom and use the crosshair to inspect price action.</p><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-secondary p-4"><p className="text-xs text-muted-foreground">Your balance</p><p className="mt-1 text-lg font-semibold">{balance.toLocaleString()} {market.symbol}</p></div><div className="rounded-2xl bg-secondary p-4"><p className="text-xs text-muted-foreground">Your value</p><p className="mt-1 text-lg font-semibold">{formatFiat(balance*market.price)}</p></div></div><div className="mt-6 rounded-2xl border border-border p-4"><div className="flex items-center gap-2"><TrendingUp size={18} className="text-primary"/><h2 className="font-semibold">Trade {market.symbol}</h2></div><div className="mt-4 grid grid-cols-2 gap-2 rounded-xl bg-secondary p-1"><button type="button" onClick={()=>setSide("buy")} className={`rounded-lg px-3 py-2 text-sm font-semibold ${side==="buy"?"bg-background shadow-sm text-success":"text-muted-foreground"}`}>Buy</button><button type="button" onClick={()=>setSide("sell")} className={`rounded-lg px-3 py-2 text-sm font-semibold ${side==="sell"?"bg-background shadow-sm text-destructive":"text-muted-foreground"}`}>Sell</button></div><label className="mt-4 block text-sm font-medium">Amount<input min="0" step="any" type="number" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} className="mt-2 w-full rounded-xl border border-input bg-background px-3 py-3" placeholder={`0.00 ${market.symbol}`}/></label><p className="mt-1 text-xs text-muted-foreground">Estimated value: {formatFiat(fiatValue)}</p><button type="button" disabled={createTrade.isPending||Number(amount)<=0} onClick={()=>void submitTrade()} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 font-semibold text-primary-foreground disabled:opacity-50">{createTrade.isPending&&<Loader2 className="animate-spin" size={17}/>} {createTrade.isPending?"Submitting…":`${side==="buy"?"Buy":"Sell"} ${market.symbol}`}</button></div><div className="mt-5 grid grid-cols-2 gap-3"><Link to="/receive" className="flex items-center justify-center gap-2 rounded-xl bg-secondary px-4 py-3 text-sm font-semibold"><ArrowDownToLine size={17}/>Receive</Link><Link to="/send" className="flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground"><Send size={17}/>Send</Link></div></section></main>;
}
